version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: wallet
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db

volumes:
  db_data:
